
service: serverless-kms-secrets
plugins:
  - serverless-kms-secrets
custom:
  # serverless-kms-secrets:
  #   secretsFile: kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml (optional)
  kmsSecrets: ${file(kms-secrets.${opt:stage, self:provider.stage}.${opt:region, self:provider.region}.yml)}  


# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs10.x
  environment:
    MY_SECRETS: ${self:custom.kmsSecrets.secrets.MY_SECRETS}
  iamRoleStatements: 
    - Effect: Allow
      Action:
      - KMS:Decrypt
      Resource: ${self:custom.kmsSecrets.keyArn} 

# The `functions` block defines what code to deployser
functions:
  kmsEncryptionDecryption:
    handler: kmsEncryptionDecryption.handler
